name: iOS Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
      
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
        working-directory: thoughtsreframer

    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: thoughtsreframer/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install certificates and provisioning profiles
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        MOBILEPROVISION: ${{ secrets.MOBILEPROVISION }}
      run: |
        # Create keychain
        security create-keychain -p "temppass" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppass" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
        # Add keychain to search list
        security list-keychains -d user -s build.keychain login.keychain
        
        # Install certificate
        echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -A
        
        # Set partition list for the keychain
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "temppass" build.keychain
        
        # Unlock keychain again after import
        security unlock-keychain -p "temppass" build.keychain
        
        # Install provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$MOBILEPROVISION" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
        
        # Extract provisioning profile UUID with better error handling
        echo "🔍 Extracting provisioning profile information..."
        security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision > /tmp/profile.plist
        
        # Try different methods to extract UUID
        PROFILE_UUID=""
        if command -v plutil >/dev/null 2>&1; then
          PROFILE_UUID=$(plutil -extract UUID raw /tmp/profile.plist 2>/dev/null || echo "")
        fi
        
        if [ -z "$PROFILE_UUID" ]; then
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /tmp/profile.plist 2>/dev/null || echo "")
        fi
        
        if [ -z "$PROFILE_UUID" ]; then
          # Fallback: extract from filename or generate
          PROFILE_UUID=$(grep -A1 "<key>UUID</key>" /tmp/profile.plist | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/' || echo "")
        fi
        
        if [ -z "$PROFILE_UUID" ]; then
          echo "❌ Failed to extract provisioning profile UUID"
          echo "📄 Profile content:"
          cat /tmp/profile.plist | head -20
          exit 1
        fi
        
        echo "PROVISIONING_PROFILE_UUID=$PROFILE_UUID" >> $GITHUB_ENV
        echo "✅ Provisioning Profile UUID: $PROFILE_UUID"
        
        # Debug keychain contents
        echo "🔍 Debugging keychain contents..."
        security list-keychains -d user
        security find-identity -v build.keychain
        
        # List all available identities for debugging
        echo "📋 Available signing identities:"
        security find-identity -v -p codesigning
        
        # Try alternative method to find certificates
        echo "🔍 Alternative certificate search:"
        security find-identity -v -p codesigning build.keychain
        
        # Detect and set certificate name with validation
        CERT_NAME=""
        
        # Try finding in specific keychain first
        CERT_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Apple Distribution\|iOS Distribution" | head -n 1 | cut -d '"' -f 2)
        
        if [ -z "$CERT_NAME" ]; then
          # Try system-wide search
          CERT_NAME=$(security find-identity -v -p codesigning | grep "Apple Distribution\|iOS Distribution" | head -n 1 | cut -d '"' -f 2)
        fi
        
        if [ -z "$CERT_NAME" ]; then
          echo "⚠️  No Distribution certificate found, checking for Development certificates..."
          CERT_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Apple Development\|iOS Development" | head -n 1 | cut -d '"' -f 2)
          
          if [ -z "$CERT_NAME" ]; then
            CERT_NAME=$(security find-identity -v -p codesigning | grep "Apple Development\|iOS Development" | head -n 1 | cut -d '"' -f 2)
          fi
          
          if [ -n "$CERT_NAME" ]; then
            echo "⚠️  Warning: Using Development certificate for App Store build. This may cause issues."
            echo "💡 Please ensure you have uploaded the correct Apple Distribution certificate."
          fi
        fi
        
        # If still no certificate found, try to extract from keychain dump
        if [ -z "$CERT_NAME" ]; then
          echo "🔍 Trying to extract certificate name from keychain dump..."
          CERT_NAME=$(security dump-keychain build.keychain | grep -A1 "Apple Development\|Apple Distribution\|iOS Development\|iOS Distribution" | grep "alis" | head -1 | cut -d'"' -f4)
        fi
        
        if [ -z "$CERT_NAME" ]; then
          echo "❌ No valid signing certificate found!"
          echo "📋 Keychain contents:"
          security dump-keychain build.keychain | grep -A5 -B5 "Apple\|iOS"
          exit 1
        fi
        
        echo "CODE_SIGN_IDENTITY=$CERT_NAME" >> $GITHUB_ENV
        echo "🔑 Using certificate: $CERT_NAME"
        
        # Validate certificate type
        if echo "$CERT_NAME" | grep -q "Development"; then
          echo "⚠️  WARNING: Using Development certificate for App Store deployment!"
          echo "💡 This build may fail during export. Please use Apple Distribution certificate."
        fi

    - name: Install dependencies
      working-directory: thoughtsreframer
      run: |
        gem install bundler
        bundle install
        pod install --repo-update

    - name: Build and Deploy
      working-directory: thoughtsreframer
      run: |
        echo "🚀 Building iOS app..."
        bundle exec fastlane beta_auto

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: thoughtsreframer/*.ipa
        retention-days: 30

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ~/Library/Logs/gym/
          thoughtsreframer/fastlane/report.xml
        retention-days: 7 